### ISSUE TITLE
Add Traceroute Functionality

### ISSUE THREAD

**Issue by ayysasha** [paulocode/multimesh#32] opened 2024-04-09 06:25 UTC
Adding the ability to do traceroutes would be great.

This functionality should also include an intuitive UI to allow the user to understand if the Traceroute is in its different states (Sent, Awaiting receipt, no receipt, etc).

**Comment by paulocode** [comment] 2024-04-10 16:55
Thank you for creating an issue. This is a duplicate of #29.

**Closed by paulocode** 2024-04-10 16:55 UTC
